"""
Phase 2: train the SentencePiece tokenizer for the pt_BR FUTO model.

Replicates the reference English tokenizer's structural layout:
  indices 0-3:    pad / bos / eos / unk
  indices 4-303:  300 user-defined symbols (declaration order = ID order)
                  - 4..27   <FUTO0>..<FUTO23>            (parity filler)
                  - 28..173 pt_BR contractions/words      (146 slots)
                  - 174..176 <XBU> <XBC> <XEC>            (REQUIRED, name-looked-up)
                  - 177..181 <XC0>..<XC4>                 (parity, only XC0 used by Android)
                  - 182..207 <CHAR_A>..<CHAR_Z>           (REQUIRED, MUST be sequential)
                  - 208..263 more pt_BR common words      (56 slots)
                  - 264..303 emoji                         (40 slots)
  indices 304-559: byte fallback <0x00>..<0xFF> (256 slots, auto-generated by SP)
  indices 560+:    learned BPE pieces from corpus

Usage:
  python 02_train_tokenizer.py --corpus /workspace/corpora/clean --out tokenizer/spm_pt_br
"""
from __future__ import annotations
import argparse
import glob
import json
from pathlib import Path

import sentencepiece as spm

# ----------------- pt_BR slot fillers (curated; refine with frequency analysis later) -----------------

# 146 pt_BR contractions / common words / bigrams (slots 28..173).
# Mix of: chat shortcuts, articles, prepositions, contractions, common verbs.
# All written with a trailing ▁ (lower-1/8 block, U+2581) where they are
# whitespace-suffix-attaching pieces — MIRRORING the English reference style
# where "I'm▁" appears with attached following-space marker.
# (SentencePiece will accept the unicode ▁ in user_defined_symbols.)
SPACE = "▁"  # ▁ — SentencePiece whitespace marker

PTBR_CHAT = [
    "vc", "vcs", "tb", "tbm", "pq", "q", "ñ", "naum", "tô", "tá", "tava", "tavah",
    "obg", "vlw", "blz", "flw", "abs", "bjs", "bj", "rs", "kk", "kkk", "kkkk",
    "kkkkk", "rsrs", "tipo", "mds", "amg", "amgs", "msm", "msmo", "dps", "agr",
    "hj", "hjj", "ngm", "tdo", "tds", "td", "tudão", "blzz", "vlww", "vamoooo",
]
PTBR_PREPOSITIONS = [
    "de", "do", "da", "dos", "das", "em", "no", "na", "nos", "nas", "por", "pelo", "pela",
    "pelos", "pelas", "para", "pra", "pro", "pras", "pros", "com", "sem", "sobre", "sob",
    "ante", "após", "até", "desde", "entre", "perante", "contra",
]
PTBR_ARTICLES_PRONOUNS = [
    "o", "a", "os", "as", "um", "uma", "uns", "umas", "este", "esta", "estes", "estas",
    "esse", "essa", "esses", "essas", "aquele", "aquela", "aqueles", "aquelas",
    "isto", "isso", "aquilo", "ele", "ela", "eles", "elas", "eu", "tu", "você", "vocês",
    "nós", "agente", "meu", "minha", "meus", "minhas", "seu", "sua", "seus", "suas",
]
PTBR_CONNECTIVES = [
    "e", "ou", "mas", "que", "porque", "porquê", "porém", "contudo", "todavia",
    "entretanto", "embora", "se", "como", "quando", "onde", "enquanto", "depois",
    "antes", "agora", "ainda", "já", "também", "tampouco", "nem", "não", "sim",
]
PTBR_COMMON_VERBS = [
    "é", "são", "foi", "foram", "será", "serão", "está", "estão", "estava", "estavam",
    "tem", "têm", "tinha", "tinham", "havia", "vai", "vão", "ia", "iam", "fazer",
    "faz", "fez", "fazem", "fazendo", "ser", "estar", "ter", "haver", "ir", "vir",
    "ficar", "ficou", "fica", "ficam", "dizer", "disse", "diz", "dizem", "saber",
    "sabe", "sabem", "achar", "acho", "acha", "acham", "queria", "quero", "quer",
    "querem", "podia", "pode", "podem", "poderia", "preciso", "precisa", "precisam",
]

# Combined: the first 146 fill slots 28..173 (with whitespace-suffix marker).
def with_suffix(words):
    return [w + SPACE for w in words]

PTBR_SLOT_28_173 = (
    with_suffix(PTBR_CHAT)
    + with_suffix(PTBR_PREPOSITIONS)
    + with_suffix(PTBR_ARTICLES_PRONOUNS)
    + with_suffix(PTBR_CONNECTIVES)
    + with_suffix(PTBR_COMMON_VERBS)
)
# Pad with <FUTO24>+ filler to exactly 146 entries
while len(PTBR_SLOT_28_173) < 146:
    PTBR_SLOT_28_173.append(f"<FUTO{24 + (len(PTBR_SLOT_28_173) - 0)}>")
PTBR_SLOT_28_173 = PTBR_SLOT_28_173[:146]
assert len(PTBR_SLOT_28_173) == 146, len(PTBR_SLOT_28_173)

# 56 more slots 208..263 — common pt_BR adverbs/bigrams/numerals
PTBR_SLOT_208_263 = with_suffix([
    "muito", "pouco", "bem", "mal", "bom", "boa", "bons", "boas", "ruim", "péssimo",
    "ótimo", "mais", "menos", "tão", "tanto", "tantos", "tantas", "todo", "toda",
    "todos", "todas", "outro", "outra", "outros", "outras", "mesmo", "mesma", "mesmos",
    "mesmas", "próprio", "própria", "alguns", "algumas", "alguém", "ninguém", "tudo",
    "nada", "algo", "cada", "qualquer", "vários", "várias",
    "logo", "cedo", "tarde", "ontem", "hoje", "amanhã", "sempre", "nunca", "jamais",
    "talvez", "aqui", "ali", "lá", "aí",
])
assert len(PTBR_SLOT_208_263) == 56, len(PTBR_SLOT_208_263)

# 40 emoji (mirror reference English's set; tuned for Brazilian audience could
# add 🇧🇷, ⚽, 🥑, 🌽, 🍻 etc., but keep the same set for v1 to maximize compat)
EMOJI = [
    "😂", "❤", "😍", "😭", "😘", "🙏", "👌", "👍", "💕", "🔥",
    "👀", "💯", "✨", "🥺", "😊", "💗", "🎂", "🎁", "🌟", "🎈",
    "💜", "💙", "✅", "😢", "😳", "💪", "💖", "🎶", "🙌", "⬅",
    "😋", "🙈", "💀", "😄", "🌹", "✌", "👉", "😞", "💛", "😜",
]
assert len(EMOJI) == 40, len(EMOJI)
assert len(set(EMOJI)) == 40, "duplicate emoji"


def build_user_defined_symbols() -> list[str]:
    """Return exactly 300 symbols in the order they should be assigned IDs 4..303."""
    symbols: list[str] = []
    # 4..27 — FUTO0..FUTO23 filler
    symbols += [f"<FUTO{i}>" for i in range(24)]
    # 28..173 — 146 pt_BR common words/contractions
    symbols += PTBR_SLOT_28_173
    # 174..176 — STRUCTURAL: required for xbu_char_autocorrect_v1
    symbols += ["<XBU>", "<XBC>", "<XEC>"]
    # 177..181 — XC0..XC4 (parity; only XC0 used by Android; declaring all 5 keeps room for future swipe)
    symbols += [f"<XC{i}>" for i in range(5)]
    # 182..207 — STRUCTURAL: <CHAR_A>..<CHAR_Z> MUST be 26 sequential IDs
    symbols += [f"<CHAR_{c}>" for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"]
    # 208..263 — 56 more pt_BR common adverbs/bigrams
    symbols += PTBR_SLOT_208_263
    # 264..303 — 40 emoji
    symbols += EMOJI
    assert len(symbols) == 300, f"Expected 300 symbols, got {len(symbols)}"
    return symbols


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", required=True, help="Glob or dir of plain-text shard files")
    ap.add_argument("--out", default="tokenizer/spm_pt_br", help="Output prefix (writes .model and .vocab)")
    ap.add_argument("--vocab-size", type=int, default=15008)
    ap.add_argument("--input-sentence-size", type=int, default=10_000_000)
    args = ap.parse_args()

    # Resolve corpus glob
    corpus = Path(args.corpus)
    if corpus.is_dir():
        files = sorted(str(p) for p in corpus.glob("shard_*.txt"))
    else:
        files = sorted(glob.glob(args.corpus))
    if not files:
        raise SystemExit(f"No corpus shards found at {args.corpus}")
    print(f"Training on {len(files)} shard(s):")
    for f in files[:5]:
        print(f"  {f}")
    if len(files) > 5:
        print(f"  ... ({len(files) - 5} more)")

    user_defined = build_user_defined_symbols()
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out + ".user_defined.json").write_text(json.dumps(user_defined, ensure_ascii=False, indent=2))
    print(f"Wrote {args.out}.user_defined.json (300 symbols)")

    spm.SentencePieceTrainer.train(
        input=",".join(files),
        input_format="text",
        model_prefix=args.out,
        vocab_size=args.vocab_size,
        character_coverage=0.9995,
        model_type="bpe",
        treat_whitespace_as_suffix=True,    # `inverted_space` feature
        user_defined_symbols=user_defined,  # 300 symbols at IDs 4..303
        pad_id=0, bos_id=1, eos_id=2, unk_id=3,  # match English reference
        input_sentence_size=args.input_sentence_size,
        shuffle_input_sentence=True,
        byte_fallback=True,
        max_sentence_length=4192,
        num_threads=8,
    )
    print(f"Wrote {args.out}.model and {args.out}.vocab")

    # Validate
    sp = spm.SentencePieceProcessor()
    sp.load(args.out + ".model")
    print(f"vocab_size={sp.get_piece_size()}")
    assert sp.get_piece_size() == args.vocab_size, "vocab size mismatch"

    # Structural assertions
    for name in ("<XBU>", "<XBC>", "<XEC>", "<XC0>"):
        i = sp.piece_to_id(name)
        assert i > 3, f"{name} not present (piece_to_id={i})"
        print(f"  {name} -> id {i}")

    # CHAR_A..CHAR_Z must be 26 sequential
    char_ids = [sp.piece_to_id(f"<CHAR_{c}>") for c in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"]
    print(f"  <CHAR_*> ids: {char_ids[0]}..{char_ids[-1]} (range {char_ids[0]}..{char_ids[0]+25})")
    assert char_ids == list(range(char_ids[0], char_ids[0] + 26)), \
        f"CHAR_A..Z not sequential: {char_ids}"

    # Whitespace-as-suffix smoke test
    sample = "Bom dia, hoje é um bom dia para programar."
    pcs = sp.encode_as_pieces(sample)
    print(f"  sample pieces: {pcs}")

    # XBU autocorrect format round-trip
    s = "Eu fui ao <XBU>mecado<XBC>mercado<XEC> ontem"
    ids = sp.encode_as_ids(s)
    decoded = sp.decode(ids)
    print(f"  XBU round-trip: {ids[:20]}... -> {decoded[:80]!r}")

    print("Tokenizer trained and validated.")


if __name__ == "__main__":
    main()
